### ISSUE TITLE
Question about "KV cache is reset to zero"

### ISSUE THREAD

**Issue by YukiChen-yuxin** [Zoeyyao27/SirLLM#1]
Hi, the SirLLM is awesome! Just curious about one point, you mentioned "DailyDialog and Grocery Shopping datasets, where the KV cache is reset to zero after each round", then how does LLM remember the info about the grocery list in the final round if the KV cache is reset.
Thanks!

**Comment by Zoeyyao27** [comment]
Hello! Thank you for your interest in our work. In our paper, a round consists of multiple turns of dialogue. Figure 8 illustrates a round of dialogue in the Grocery Shopping dataset. Please feel free to check it out.

**Comment by YukiChen-yuxin** [comment]
Got it, thanks!
